# fly.toml file generated for jb-cockroach-596 on 2021-07-22T22:23:01+02:00

app = "jb-cockroach-596"

kill_signal = "SIGINT"
kill_timeout = 120

[metrics]
  path = "/_status/vars"
  port = 8080

[mount]
  destination = "/cockroach/cockroach-data"
  source = "cdb_data"
